# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-04-18 15:25:21
"""
import arcpy
#Ensure that we can overwrite it for reuse.
arcpy.env.overwriteOutput = True
#Set Workspace and referenced locations. 
arcpy.env.workspace = "C:\Code\Final\Treatment.gdb"
TreatmentArea = "C:\\Code\\Final\\Treatment\\Treatment.gdb\\TreatmentArea"
Updated_Input_Table="C:/Code/Final\Treatment.gdb\\TreatmentArea"   
WeedLocation = "C:\\Code\\Final\\Treatment\\Treatment.gdb\\WeedLocation"
# Imput required treatment zone here.
Distance = "1000 Meters"
#In order to save on product, make sure that the buffer has disolved borders. 
Dissolve_Type = "ALL"
Field_Name = "Order"
# below is the expresion that converts square yards into product specific application and bag size. 
Expression = "!Shape_Area! * 1.19599005/10000/50"
# Process: Perform the Buffer. All parameters are either shown above or listed in green below. 
arcpy.analysis.Buffer(in_features=WeedLocation, out_feature_class=TreatmentArea, buffer_distance_or_field=Distance, line_side="FULL", line_end_type="ROUND", dissolve_option=Dissolve_Type, dissolve_field=[], method="PLANAR")
# Proccess: Add a field that we can edited for finding order amount.
arcpy.management.AddField(in_table=TreatmentArea, field_name=Field_Name, field_type="LONG", field_precision=None, field_scale=None, field_length=None, field_alias="", field_is_nullable="NULLABLE", field_is_required="NON_REQUIRED", field_domain="")[0]
# Analysis: Calculate the amount needed with the product specific expresion found above and list it in the "Order" field.
arcpy.management.CalculateField(in_table=TreatmentArea, field="Order_", expression=Expression, expression_type="PYTHON3", code_block="", field_type="TEXT", enforce_domains="NO_ENFORCE_DOMAINS")[0]


